# Site settings
title: Stephen Melinyshyn
email: stephen.melinyshyn@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
   This is my personal site for my blog, information
   about what I'm working on, and more. These are
   things that are interesting to me and, possibly, to you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://melinysh.me" # the base hostname & protocol for your site
twitter_username: melinysh
github_username: melinysh
author: melinysh

# Build settings
markdown_ext:  markdown,mkdown,mkdn,mkd,md
markdown: kramdown

kramdown:
      input: GFM
      syntax_highlighter: rouge

# Gems to include
gems:
      - jekyll-seo-tag
#redcarpet:
# extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
