# Site settings
title: Stephen Melinyshyn
email: stephen.melinyshyn@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
   This is my personal site for my blog, information
   about what I'm working on, and more. These are
   things that are interesting to me and, hopefully, to you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://melinysh.me" # the base hostname & protocol for your site
twitter_username: melinysh
github_username: melinysh

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

# Gems to include
gems:
      - jekyll-redirect-from


redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
