# Site settings
title: Stephen Melinyshyn
email: 
description: > # this means to ignore newlines until "baseurl:"
   This site is a place for me write about my experiences in 
    code, school, and life. These will be things that are 
    interesting to me and, hopefully, to you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://melinysh.me" # the base hostname & protocol for your site
twitter_username: melinysh
github_username: melinysh

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
